package com.comviva.proxylocation.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-08-16T21:27:59.537-03:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://service.proxyLocation.comviva.com", name = "proxyLocationServiceImpl")
@XmlSeeAlso({com.comviva.proxylocation.schema.ObjectFactory.class, ObjectFactory.class})
public interface ProxyLocationServiceImpl {

    @WebMethod
    @RequestWrapper(localName = "cancelLocation", targetNamespace = "http://service.proxyLocation.comviva.com", className = "com.comviva.proxylocation.service.CancelLocation")
    @ResponseWrapper(localName = "proxyCancelLocationResponse", targetNamespace = "http://service.proxyLocation.comviva.com", className = "com.comviva.proxylocation.service.ProxyCancelLocationResponse")
    @WebResult(name = "proxyCancelLocationReturn", targetNamespace = "http://service.proxyLocation.comviva.com")
    public com.comviva.proxylocation.schema.ProxyCancelLocationResponse cancelLocation(

        @WebParam(name = "proxyCancelLocationRequest", targetNamespace = "http://service.proxyLocation.comviva.com")
        com.comviva.proxylocation.schema.ProxyCancelLocationRequest proxyCancelLocationRequest
    );

    @WebMethod
    @RequestWrapper(localName = "getLocation", targetNamespace = "http://service.proxyLocation.comviva.com", className = "com.comviva.proxylocation.service.GetLocation")
    @ResponseWrapper(localName = "proxyLocationResponse", targetNamespace = "http://service.proxyLocation.comviva.com", className = "com.comviva.proxylocation.service.ProxyLocationResponse")
    @WebResult(name = "proxyLocationReturn", targetNamespace = "http://service.proxyLocation.comviva.com")
    public com.comviva.proxylocation.schema.ProxyLocationResponse getLocation(

        @WebParam(name = "proxyLocationRequest", targetNamespace = "http://service.proxyLocation.comviva.com")
        com.comviva.proxylocation.schema.ProxyLocationRequest proxyLocationRequest
    );
}
