
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.comviva.proxylocation.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-08-16T21:27:59.467-03:00
 * Generated source version: 3.3.4
 *
 */

@javax.jws.WebService(
                      serviceName = "proxyLocationServiceImplService",
                      portName = "proxyLocationServiceImpl",
                      targetNamespace = "http://service.proxyLocation.comviva.com",
                      wsdlLocation = "file:/C:/Users/tbel/Documents/workspace_new/ASA_HLRLocationServices/WebContent/serviceLocation.wsdl",
                      endpointInterface = "com.comviva.proxylocation.service.ProxyLocationServiceImpl")

public class ProxyLocationServiceImplImpl implements ProxyLocationServiceImpl {

    private static final Logger LOG = Logger.getLogger(ProxyLocationServiceImplImpl.class.getName());

    /* (non-Javadoc)
     * @see com.comviva.proxylocation.service.ProxyLocationServiceImpl#cancelLocation(com.comviva.proxylocation.schema.ProxyCancelLocationRequest proxyCancelLocationRequest)*
     */
    public com.comviva.proxylocation.schema.ProxyCancelLocationResponse cancelLocation(com.comviva.proxylocation.schema.ProxyCancelLocationRequest proxyCancelLocationRequest) {
        LOG.info("Executing operation cancelLocation");
        System.out.println(proxyCancelLocationRequest);
        try {
            com.comviva.proxylocation.schema.ProxyCancelLocationResponse _return = new com.comviva.proxylocation.schema.ProxyCancelLocationResponse();
            _return.setResultCode("ResultCode-347795588");
            _return.setResultDescription("ResultDescription-1945683729");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.comviva.proxylocation.service.ProxyLocationServiceImpl#getLocation(com.comviva.proxylocation.schema.ProxyLocationRequest proxyLocationRequest)*
     */
    public com.comviva.proxylocation.schema.ProxyLocationResponse getLocation(com.comviva.proxylocation.schema.ProxyLocationRequest proxyLocationRequest) {
        LOG.info("Executing operation getLocation");
        System.out.println(proxyLocationRequest);
        try {
            com.comviva.proxylocation.schema.ProxyLocationResponse _return = new com.comviva.proxylocation.schema.ProxyLocationResponse();
            _return.setResultCode("ResultCode99268668");
            _return.setResultDescription("ResultDescription-1945500359");
            _return.setNet("Net618269202");
            _return.setRawData("RawData-1315985221");
            _return.setMobileCountryCode("MobileCountryCode1877116541");
            _return.setMobileNetworkCode("MobileNetworkCode953123633");
            _return.setLocationAreaCode("LocationAreaCode721892085");
            _return.setCellIdentityOrSAI("CellIdentityOrSAI-540125865");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
