package com.comviva.proxylocation.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-08-16T21:27:59.550-03:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "proxyLocationServiceImplService",
                  wsdlLocation = "file:/C:/Users/tbel/Documents/workspace_new/ASA_HLRLocationServices/WebContent/serviceLocation.wsdl",
                  targetNamespace = "http://service.proxyLocation.comviva.com")
public class ProxyLocationServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.proxyLocation.comviva.com", "proxyLocationServiceImplService");
    public final static QName ProxyLocationServiceImpl = new QName("http://service.proxyLocation.comviva.com", "proxyLocationServiceImpl");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/tbel/Documents/workspace_new/ASA_HLRLocationServices/WebContent/serviceLocation.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProxyLocationServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/tbel/Documents/workspace_new/ASA_HLRLocationServices/WebContent/serviceLocation.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProxyLocationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProxyLocationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyLocationServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProxyLocationServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProxyLocationServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProxyLocationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProxyLocationServiceImpl
     */
    @WebEndpoint(name = "proxyLocationServiceImpl")
    public ProxyLocationServiceImpl getProxyLocationServiceImpl() {
        return super.getPort(ProxyLocationServiceImpl, ProxyLocationServiceImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProxyLocationServiceImpl
     */
    @WebEndpoint(name = "proxyLocationServiceImpl")
    public ProxyLocationServiceImpl getProxyLocationServiceImpl(WebServiceFeature... features) {
        return super.getPort(ProxyLocationServiceImpl, ProxyLocationServiceImpl.class, features);
    }

}
